<?xml version="1.0" encoding="utf-8"?><Database Name="SalonMS" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VSETKTT;Initial Catalog=SalonMS;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SalonMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_ExpenseHead" Member="tbl_ExpenseHeads">
    <Type Name="tbl_ExpenseHead">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HeadName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PaymentMode" Member="tbl_PaymentModes">
    <Type Name="tbl_PaymentMode">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ClientMaster" Member="tbl_ClientMasters">
    <Type Name="tbl_ClientMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AssignTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Service" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_CouponMaster" Member="tbl_CouponMasters">
    <Type Name="tbl_CouponMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CouponCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MinimumBillingAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MaxDiscountAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CouponPerUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Validity" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RewardPoint" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MembershipMaster" Member="tbl_MembershipMasters">
    <Type Name="tbl_MembershipMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MembershipType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MembershipPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RewardPointOnPurchase" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountOnService" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountOnServiceType" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountOnProduct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountOnProductType" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountOnPackage" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountOnPackageType" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="RewardPointBoost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinimumRewardPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinimumBillAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PackageDetailMaster" Member="tbl_PackageDetailMasters">
    <Type Name="tbl_PackageDetailMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackageId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PackageMaster" Member="tbl_PackageMasters">
    <Type Name="tbl_PackageMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageValidity" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PackagePrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ServiceMaster" Member="tbl_ServiceMasters">
    <Type Name="tbl_ServiceMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="RewardPoints" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ServiceFor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_InquiryMaster" Member="tbl_InquiryMasters">
    <Type Name="tbl_InquiryMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InquiryFor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InquiryType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Response" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateToFollow" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SourceOfInquiry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LeadBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LeadStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ServiceProviderMaster" Member="tbl_ServiceProviderMasters">
    <Type Name="tbl_ServiceProviderMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ServiceComission" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ProductComission" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="WorkingHourStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkingHourEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MonthlySalary" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ServiceProviderType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmergencyContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfJoinning" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdProofPhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ServiceProviderPhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_StaffMaster" Member="tbl_StaffMasters">
    <Type Name="tbl_StaffMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EmployeeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkingHourStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkingHourEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MonthlySalary" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="EmergencyContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfJoining" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdProofPhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BranchMaster" Member="tbl_BranchMasters">
    <Type Name="tbl_BranchMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PINcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LandMark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WhatsApp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GoogleMapLocation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GSTNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManagerMobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManagerEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Loginid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BranchPhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BranchType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ExpenseMaster" Member="tbl_ExpenseMasters">
    <Type Name="tbl_ExpenseMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExpenseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TypeOfExpense" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HeadId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PaymentModeId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Cancel Delete]" Member="Cancel_Delete" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_CustomerMaster" Member="tbl_CustomerMasters">
    <Type Name="tbl_CustomerMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WalletAccount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OpeningBalance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_WalletTransaction" Member="tbl_WalletTransactions">
    <Type Name="tbl_WalletTransaction">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TransactionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceNo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TransactionFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TransactionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SuplierMaster" Member="tbl_SuplierMasters">
    <Type Name="tbl_SuplierMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SuplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SuplierMobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SuplierAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OpeningBalance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GSTNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_StokeInOutMaster" Member="tbl_StokeInOutMasters">
    <Type Name="tbl_StokeInOutMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SuplierId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SuplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalQuantity" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalTaxableAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalGST" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalIGST" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalCGST" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalSGST" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NetAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_StockInOutDetailMaster" Member="tbl_StockInOutDetailMasters">
    <Type Name="tbl_StockInOutDetailMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StockInOutId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HSNCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductDetail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManufactureDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DiscountType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiscountPercentage" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TaxableAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GSTPercentage" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GSTAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CGSTamount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SGSTamount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IGSTamount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Netamount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Unit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_OTPMaster" Member="tbl_OTPMasters">
    <Type Name="tbl_OTPMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OTPfor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTPBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTPNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExpiryStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FKId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_NewsMaster" Member="tbl_NewsMasters">
    <Type Name="tbl_NewsMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NewsHeading" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NewsDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeeId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NewsStyle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>